name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 毎日JST 9:00に更新
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: drgnxd
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Tokyo
          # ファイルの保存先を指定
          filename: github-metrics.svg
